#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlsongBroadcasting.Resource", IsApplication=true)]

namespace AlsongBroadcasting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alban_52 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Headphones = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Loading = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Image_logo = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Text_Title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Text_URL = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int Text_label = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int ad = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int button_Back = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int button_PlayAndStop = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int listView1 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int myButton = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int relativeLayout1 = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int textView_Broadcasting = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int textView_Title = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int webView1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int webView2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int webView3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int webView4 = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BroadcastingList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomRow_WebViewBase = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Playing = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
